import { createFileRoute } from '@tanstack/react-router'
import { useServerFn } from '@tanstack/react-start'
import { useEffect, useState } from 'react'
import { ConversationCharts } from '../components/ConversationCharts'
import { AssessmentCharts } from '../components/AssessmentCharts'

// These would be generated by tanstack's server function client, but for now we'll just call fetch directly for clarity.
// In your codebase you would `import { getUserConversations } from '../api/conversations'` etc.

export const Route = createFileRoute('/dashboard')({
  component: DashboardPage,
})

import { getUserConversations } from '../api/conversations'
import { getUserAssessments } from '../api/assessment'

function DashboardPage() {
  const getUserConversationsFn = useServerFn(getUserConversations)
  const getUserAssessmentsFn = useServerFn(getUserAssessments)
  const [conversationData, setConversationData] = useState<any[]>([])
  const [conversationFiltered, setConversationFiltered] = useState<any[]>([])
  const [conversationLoading, setConversationLoading] = useState(true)
  const [conversationRefreshing, setConversationRefreshing] = useState(false)
  const [conversationError, setConversationError] = useState<string | null>(null)
  const [conversationDateFilter, setConversationDateFilter] = useState('')
  const [assessmentData, setAssessmentData] = useState<any[]>([])
  const [assessmentFiltered, setAssessmentFiltered] = useState<any[]>([])
  const [assessmentLoading, setAssessmentLoading] = useState(true)
  const [assessmentRefreshing, setAssessmentRefreshing] = useState(false)
  const [assessmentError, setAssessmentError] = useState<string | null>(null)
  const [assessmentDateFilter, setAssessmentDateFilter] = useState('')

  const applyConversationFilter = (
    items: any[],
    dateFilterValue: string,
  ): any[] => {
    if (!dateFilterValue) return items
    return items.filter(item => item.date && item.date.startsWith(dateFilterValue))
  }

  const applyAssessmentFilter = (items: any[], dateFilterValue: string): any[] => {
    if (!dateFilterValue) return items
    return items.filter(item => item.date && item.date.startsWith(dateFilterValue))
  }

  const loadConversations = (dateFilterValue: string) => {
    return getUserConversationsFn()
      .then(json => {
        if (json.success) {
          setConversationData(json.data)
          setConversationFiltered(applyConversationFilter(json.data, dateFilterValue))
          setConversationError(null)
        } else {
          setConversationError(json.reason)
        }
      })
      .catch(() => setConversationError('Could not load conversation data'))
  }

  const loadAssessments = (dateFilterValue: string) => {
    return getUserAssessmentsFn()
      .then(json => {
        if (json.success) {
          setAssessmentData(json.data)
          setAssessmentFiltered(applyAssessmentFilter(json.data, dateFilterValue))
          setAssessmentError(null)
        } else {
          setAssessmentError(json.reason)
        }
      })
      .catch(() => setAssessmentError('Could not load assessment data'))
  }

  useEffect(() => {
    let ignore = false
    setConversationLoading(true)
    setAssessmentLoading(true)
    setConversationError(null)
    setAssessmentError(null)

    Promise.all([
      loadConversations(conversationDateFilter),
      loadAssessments(assessmentDateFilter),
    ]).finally(() => {
      if (!ignore) {
        setConversationLoading(false)
        setAssessmentLoading(false)
      }
    })

    return () => {
      ignore = true
    }
  }, [getUserConversationsFn, getUserAssessmentsFn])

  useEffect(() => {
    setConversationFiltered(
      applyConversationFilter(conversationData, conversationDateFilter),
    )
  }, [conversationDateFilter, conversationData])

  useEffect(() => {
    setAssessmentFiltered(applyAssessmentFilter(assessmentData, assessmentDateFilter))
  }, [assessmentDateFilter, assessmentData])

  const handleReloadConversations = () => {
    setConversationRefreshing(true)
    setConversationError(null)
    void loadConversations(conversationDateFilter).finally(() =>
      setConversationRefreshing(false),
    )
  }

  const handleReloadAssessments = () => {
    setAssessmentRefreshing(true)
    setAssessmentError(null)
    void loadAssessments(assessmentDateFilter).finally(() =>
      setAssessmentRefreshing(false),
    )
  }

  return (
    <main className="page-wrap px-4 pb-8 pt-14">
      <section className="island-shell rise-in relative overflow-hidden rounded-4xl px-6 py-10 sm:px-10 sm:py-14">
        <div className="pointer-events-none absolute -left-20 -top-24 h-56 w-56 rounded-full bg-[radial-gradient(circle,rgba(79,184,178,0.32),transparent_66%)]" />
        <div className="pointer-events-none absolute -bottom-20 -right-20 h-56 w-56 rounded-full bg-[radial-gradient(circle,rgba(47,106,74,0.18),transparent_66%)]" />
        <h1 className="display-title mb-6 text-3xl sm:text-4xl font-bold text-(--sea-ink)">
          Conversation Dashboard
        </h1>
        <p className="mb-8 max-w-2xl text-sm text-(--sea-ink-soft) sm:text-base">
          Track conversation sessions and TICS assessment trends in one place.
        </p>

        <h2 className="mb-4 text-xl font-semibold text-(--sea-ink)">
          Conversations
        </h2>
        <div className="mb-6 flex flex-wrap items-center gap-3">
          <label className="font-semibold text-(--sea-ink-soft) text-sm flex items-center gap-1">
            Filter by Date:
            <input
              type="date"
              value={conversationDateFilter}
              onChange={e => setConversationDateFilter(e.target.value)}
              className="ml-2 rounded border border-[rgba(50,143,151,0.25)] px-2 py-1 text-sm bg-transparent text-(--sea-ink) focus:outline-none focus:ring focus:border-(--lagoon-deep)"
              style={{ minWidth: 140 }}
            />
          </label>
          <button
            onClick={() => { setConversationDateFilter('') }}
            className="rounded-full border border-[rgba(47,106,74,0.25)] bg-white/60 px-4 py-1.5 text-xs font-semibold text-(--sea-ink) transition hover:bg-[rgba(79,184,178,0.14)] ml-2"
          >
            CLEAR FILTER
          </button>
          <div className="flex-1" />
          <button
            onClick={handleReloadConversations}
            disabled={conversationRefreshing}
            className="rounded-full border border-[rgba(47,106,74,0.25)] bg-white/60 px-4 py-1.5 text-xs font-semibold text-(--sea-ink) transition hover:bg-[rgba(79,184,178,0.14)]"
          >
            {conversationRefreshing ? 'REFRESHING...' : 'RELOAD'}
          </button>
        </div>
        {conversationLoading && (
          <div className="py-10 flex justify-center items-center">
            <span className="text-(--sea-ink-soft)">Loading...</span>
          </div>
        )}
        {conversationError && (
          <div className="py-6 text-red-600 font-semibold">
            Error: {conversationError}
          </div>
        )}
        {!conversationLoading && !conversationError && (
          <>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-(--chip-line)">
                <thead>
                  <tr>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Date</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Time</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Duration (min)</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Speech Activity</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Avg Speech Rate</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Words Spoken</th>
                  </tr>
                </thead>
                <tbody>
                  {conversationFiltered.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-2 py-6 text-center text-(--sea-ink-soft)">
                        No conversations found.
                      </td>
                    </tr>
                  ) : (
                    conversationFiltered.map((item, i) => (
                      <tr key={i} className="even:bg-[rgba(79,184,178,0.06)]">
                        <td className="px-2 py-2">{item.date || '-'}</td>
                        <td className="px-2 py-2">{item.time || '-'}</td>
                        <td className="px-2 py-2">{item.duration != null ? item.duration : '-'}</td>
                        <td className="px-2 py-2">{item.speechActivity != null ? item.speechActivity : '-'}</td>
                        <td className="px-2 py-2">{item.avgSpeechRate != null ? item.avgSpeechRate : '-'}</td>
                        <td className="px-2 py-2">{item.wordsSpoken != null ? item.wordsSpoken : '-'}</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
            <ConversationCharts conversations={conversationFiltered} />
          </>
        )}

        <div className="my-10 h-px w-full bg-(--chip-line)" />

        <h2 className="mb-4 text-xl font-semibold text-(--sea-ink)">
          TICS Assessments
        </h2>
        <div className="mb-6 flex flex-wrap items-center gap-3">
          <label className="font-semibold text-(--sea-ink-soft) text-sm flex items-center gap-1">
            Filter by Date:
            <input
              type="date"
              value={assessmentDateFilter}
              onChange={e => setAssessmentDateFilter(e.target.value)}
              className="ml-2 rounded border border-[rgba(50,143,151,0.25)] px-2 py-1 text-sm bg-transparent text-(--sea-ink) focus:outline-none focus:ring focus:border-(--lagoon-deep)"
              style={{ minWidth: 140 }}
            />
          </label>
          <button
            onClick={() => { setAssessmentDateFilter('') }}
            className="rounded-full border border-[rgba(47,106,74,0.25)] bg-white/60 px-4 py-1.5 text-xs font-semibold text-(--sea-ink) transition hover:bg-[rgba(79,184,178,0.14)] ml-2"
          >
            CLEAR FILTER
          </button>
          <div className="flex-1" />
          <button
            onClick={handleReloadAssessments}
            disabled={assessmentRefreshing}
            className="rounded-full border border-[rgba(47,106,74,0.25)] bg-white/60 px-4 py-1.5 text-xs font-semibold text-(--sea-ink) transition hover:bg-[rgba(79,184,178,0.14)]"
          >
            {assessmentRefreshing ? 'REFRESHING...' : 'RELOAD'}
          </button>
        </div>
        {assessmentLoading && (
          <div className="py-10 flex justify-center items-center">
            <span className="text-(--sea-ink-soft)">Loading...</span>
          </div>
        )}
        {assessmentError && (
          <div className="py-6 text-red-600 font-semibold">
            Error: {assessmentError}
          </div>
        )}
        {!assessmentLoading && !assessmentError && (
          <>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-(--chip-line)">
                <thead>
                  <tr>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Date</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Time</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Orientation</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Attention</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Immediate Recall</th>
                    <th className="px-2 py-2 text-left text-xs font-semibold text-(--sea-ink-soft)">Total Score</th>
                  </tr>
                </thead>
                <tbody>
                  {assessmentFiltered.length === 0 ? (
                    <tr>
                      <td colSpan={6} className="px-2 py-6 text-center text-(--sea-ink-soft)">
                        No assessments found.
                      </td>
                    </tr>
                  ) : (
                    assessmentFiltered.map((item, i) => (
                      <tr key={i} className="even:bg-[rgba(79,184,178,0.06)]">
                        <td className="px-2 py-2">{item.date || '-'}</td>
                        <td className="px-2 py-2">{item.time || '-'}</td>
                        <td className="px-2 py-2">{item.orientation != null ? `${item.orientation}/2` : '-'}</td>
                        <td className="px-2 py-2">{item.attention != null ? `${item.attention}/2` : '-'}</td>
                        <td className="px-2 py-2">{item.immediateRecall != null ? `${item.immediateRecall}/1` : '-'}</td>
                        <td className="px-2 py-2">{item.totalScore != null ? `${item.totalScore}/5` : '-'}</td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>
            <AssessmentCharts assessments={assessmentFiltered} />
          </>
        )}
      </section>
    </main>
  )
}
