import { createFileRoute } from '@tanstack/react-router'
import { useServerFn } from '@tanstack/react-start'
import { useEffect, useState } from 'react'

// These would be generated by tanstack's server function client, but for now we'll just call fetch directly for clarity.
// In your codebase you would `import { getUserConversations } from '../api/conversations'` etc.

export const Route = createFileRoute('/dashboard')({
  component: DashboardPage,
})

import { getUserConversations } from '../api/conversations'

function DashboardPage() {
  const getUserConversationsFn = useServerFn(getUserConversations)
  const [data, setData] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [dateFilter, setDateFilter] = useState('')
  const [filtered, setFiltered] = useState<any[]>([])
  const [refreshing, setRefreshing] = useState(false)

  // Fetch conversations directly from the server function, not via HTTP
  useEffect(() => {
    let ignore = false
    setLoading(true)
    setError(null)
    getUserConversationsFn()
      .then(json => {
        if (!ignore) {
          if (json.success) {
            setData(json.data)
            setFiltered(json.data)
            setError(null)
          } else {
            setError(json.reason)
          }
        }
      })
      .catch(() => {
        if (!ignore) setError('Could not load data')
      })
      .finally(() => {
        if (!ignore) setLoading(false)
      })
    return () => { ignore = true }
  }, [getUserConversationsFn])

  useEffect(() => {
    if (!dateFilter) {
      setFiltered(data)
    } else {
      setFiltered(
        data.filter(item => item.date && item.date.startsWith(dateFilter))
      )
    }
  }, [dateFilter, data])

  const handleReload = () => {
    setRefreshing(true)
    setError(null)
    getUserConversationsFn()
      .then(json => {
        if (json.success) {
          setData(json.data)
          setFiltered(dateFilter
            ? json.data.filter((item: any) =>
                item.date && item.date.startsWith(dateFilter)
              )
            : json.data
          )
        } else {
          setError(json.reason)
        }
      })
      .catch(() => setError('Could not reload data'))
      .finally(() => setRefreshing(false))
  }

  return (
    <main className="page-wrap px-4 pb-8 pt-14">
      <section className="island-shell rise-in relative overflow-hidden rounded-[2rem] px-6 py-10 sm:px-10 sm:py-14">
        <div className="pointer-events-none absolute -left-20 -top-24 h-56 w-56 rounded-full bg-[radial-gradient(circle,rgba(79,184,178,0.32),transparent_66%)]" />
        <div className="pointer-events-none absolute -bottom-20 -right-20 h-56 w-56 rounded-full bg-[radial-gradient(circle,rgba(47,106,74,0.18),transparent_66%)]" />
        <h1 className="display-title mb-6 text-3xl sm:text-4xl font-bold text-[var(--sea-ink)]">
          Conversation Dashboard
        </h1>
        <div className="mb-6 flex flex-wrap items-center gap-3">
          <label className="font-semibold text-[var(--sea-ink-soft)] text-sm flex items-center gap-1">
            Filter by Date:
            <input
              type="date"
              value={dateFilter}
              onChange={e => setDateFilter(e.target.value)}
              className="ml-2 rounded border border-[rgba(50,143,151,0.25)] px-2 py-1 text-sm bg-transparent text-[var(--sea-ink)] focus:outline-none focus:ring focus:border-[var(--lagoon-deep)]"
              style={{ minWidth: 140 }}
            />
          </label>
          <button
            onClick={() => { setDateFilter('') }}
            className="rounded-full border border-[rgba(47,106,74,0.25)] bg-white/60 px-4 py-1.5 text-xs font-semibold text-[var(--sea-ink)] transition hover:bg-[rgba(79,184,178,0.14)] ml-2"
          >
            CLEAR FILTER
          </button>
          <div className="flex-1" />
          <button
            onClick={handleReload}
            disabled={refreshing}
            className="rounded-full border border-[rgba(47,106,74,0.25)] bg-white/60 px-4 py-1.5 text-xs font-semibold text-[var(--sea-ink)] transition hover:bg-[rgba(79,184,178,0.14)]"
          >
            {refreshing ? 'REFRESHING...' : 'RELOAD'}
          </button>
        </div>
        {loading && (
          <div className="py-10 flex justify-center items-center">
            <span className="text-[var(--sea-ink-soft)]">Loading...</span>
          </div>
        )}
        {error && (
          <div className="py-6 text-red-600 font-semibold">
            Error: {error}
          </div>
        )}
        {!loading && !error && (
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-[var(--chip-line)]">
              <thead>
                <tr>
                  <th className="px-2 py-2 text-left text-xs font-semibold text-[var(--sea-ink-soft)]">Date</th>
                  <th className="px-2 py-2 text-left text-xs font-semibold text-[var(--sea-ink-soft)]">Time</th>
                  <th className="px-2 py-2 text-left text-xs font-semibold text-[var(--sea-ink-soft)]">Duration (min)</th>
                  <th className="px-2 py-2 text-left text-xs font-semibold text-[var(--sea-ink-soft)]">Speech Activity</th>
                  <th className="px-2 py-2 text-left text-xs font-semibold text-[var(--sea-ink-soft)]">Avg Speech Rate</th>
                  <th className="px-2 py-2 text-left text-xs font-semibold text-[var(--sea-ink-soft)]">Words Spoken</th>
                </tr>
              </thead>
              <tbody>
                {filtered.length === 0 ? (
                  <tr>
                    <td colSpan={6} className="px-2 py-6 text-center text-[var(--sea-ink-soft)]">
                      No conversations found.
                    </td>
                  </tr>
                ) : (
                  filtered.map((item, i) => (
                    <tr key={i} className="even:bg-[rgba(79,184,178,0.06)]">
                      <td className="px-2 py-2">{item.date || '-'}</td>
                      <td className="px-2 py-2">{item.time || '-'}</td>
                      <td className="px-2 py-2">{item.duration != null ? item.duration : '-'}</td>
                      <td className="px-2 py-2">{item.speechActivity != null ? item.speechActivity : '-'}</td>
                      <td className="px-2 py-2">{item.avgSpeechRate != null ? item.avgSpeechRate : '-'}</td>
                      <td className="px-2 py-2">{item.wordsSpoken != null ? item.wordsSpoken : '-'}</td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </main>
  )
}
